# Sistema no lineal con `fsolve` y Jacobiano explícito

## Planteamiento del problema

Considere el sistema:

\[
f_1(x,y,z)=e^x+y-z^2-1=0
\]

\[
f_2(x,y,z)=x^2+y^2+z^2-6=0
\]

\[
f_3(x,y,z)=x+y+z-1=0
\]

Ahora se resolverá el sistema usando `fsolve`, pero además se suministrará de manera explícita la matriz Jacobiana.

## ¿Qué es el Jacobiano?

Para un sistema de \(n\) ecuaciones no lineales con \(n\) incógnitas, el Jacobiano es la matriz de derivadas parciales:

\[
J(x,y,z)=
\begin{bmatrix}
\dfrac{\partial f_1}{\partial x} & \dfrac{\partial f_1}{\partial y} & \dfrac{\partial f_1}{\partial z}\\
\dfrac{\partial f_2}{\partial x} & \dfrac{\partial f_2}{\partial y} & \dfrac{\partial f_2}{\partial z}\\
\dfrac{\partial f_3}{\partial x} & \dfrac{\partial f_3}{\partial y} & \dfrac{\partial f_3}{\partial z}
\end{bmatrix}
\]

En este caso:

\[
\frac{\partial f_1}{\partial x}=e^x, \qquad
\frac{\partial f_1}{\partial y}=1, \qquad
\frac{\partial f_1}{\partial z}=-2z
\]

\[
\frac{\partial f_2}{\partial x}=2x, \qquad
\frac{\partial f_2}{\partial y}=2y, \qquad
\frac{\partial f_2}{\partial z}=2z
\]

\[
\frac{\partial f_3}{\partial x}=1, \qquad
\frac{\partial f_3}{\partial y}=1, \qquad
\frac{\partial f_3}{\partial z}=1
\]

Por tanto,

\[
J(x,y,z)=
\begin{bmatrix}
e^x & 1 & -2z\\
2x & 2y & 2z\\
1 & 1 & 1
\end{bmatrix}
\]

## 1. Importación de librerías

In [1]:
import numpy as np
from scipy.optimize import fsolve

## 2. Definición del sistema

In [2]:
def sistema(vars):
    x, y, z = vars

    f1 = np.exp(x) + y - z**2 - 1
    f2 = x**2 + y**2 + z**2 - 6
    f3 = x + y + z - 1

    return [f1, f2, f3]

## 3. Definición del Jacobiano explícito

In [3]:
def jacobiano(vars):
    x, y, z = vars

    J = np.array([
        [np.exp(x), 1.0, -2.0*z],
        [2.0*x, 2.0*y, 2.0*z],
        [1.0, 1.0, 1.0]
    ])

    return J

## 4. Punto inicial

Se tomará como punto de partida:

\[
(x_0,y_0,z_0)=(1,1,-1)
\]

In [4]:
x0 = [1.0, 1.0, -1.0]
x0

[1.0, 1.0, -1.0]

## 5. Solución con `fsolve` suministrando el Jacobiano

En `fsolve`, el Jacobiano se pasa mediante el argumento `fprime`.

In [5]:
solucion = fsolve(sistema, x0, fprime=jacobiano)
solucion

/var/folders/yh/_2yfx04d3qn7npt0_n8_st8h0000gn/T/ipykernel_2012/1618091681.py:1: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last five Jacobian evaluations.
  solucion = fsolve(sistema, x0, fprime=jacobiano)


array([ 0.57545464,  1.79484741, -1.57408154])

## 6. Resultados

In [6]:
x, y, z = solucion

print("Solución encontrada:")
print(f"x = {x:.8f}")
print(f"y = {y:.8f}")
print(f"z = {z:.8f}")

Solución encontrada:
x = 0.57545464
y = 1.79484741
z = -1.57408154


## 7. Verificación de residuos

In [7]:
residuos = sistema(solucion)

print("Residuos del sistema:")
for i, r in enumerate(residuos, start=1):
    print(f"f{i} = {r:.12e}")

Residuos del sistema:
f1 = 9.505336542662e-02
f2 = 3.035796236467e-02
f3 = -2.037794971155e-01


## 8. Evaluación del Jacobiano en la solución

Esto permite discutir si la matriz está bien condicionada o no cerca de la raíz.

In [8]:
J_sol = jacobiano(solucion)
print("Jacobiano evaluado en la solución:")
print(J_sol)

Jacobiano evaluado en la solución:
[[ 1.77793866  1.          3.14816308]
 [ 1.15090927  3.58969482 -3.14816308]
 [ 1.          1.          1.        ]]


## 9. Discusión didáctica

### Ventajas de usar Jacobiano explícito

1. Se aprovecha información analítica del problema.
2. Puede mejorar la estabilidad y rapidez de convergencia.
3. Ayuda a que el estudiante entienda la base matemática del método de Newton para sistemas.

### Idea clave

Cuando no se suministra el Jacobiano, `fsolve` lo aproxima numéricamente.  
Cuando sí se entrega, el método puede volverse más transparente y más cercano al desarrollo teórico visto en clase.

In [9]:
# Comparación opcional: resolver sin Jacobiano explícito
solucion_sin_J = fsolve(sistema, x0)

print("Solución sin Jacobiano explícito:")
print(solucion_sin_J)

print("\nDiferencia entre ambas soluciones:")
print(solucion - solucion_sin_J)

Solución sin Jacobiano explícito:
[ 0.57545464  1.7948474  -1.57408154]

Diferencia entre ambas soluciones:
[-7.07343972e-09  4.82236517e-09  2.60802513e-09]


/var/folders/yh/_2yfx04d3qn7npt0_n8_st8h0000gn/T/ipykernel_2012/3531197385.py:2: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last five Jacobian evaluations.
  solucion_sin_J = fsolve(sistema, x0)
